/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { WastageService } from "../wastage.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WastageCreateInput } from "./WastageCreateInput";
import { Wastage } from "./Wastage";
import { WastageFindManyArgs } from "./WastageFindManyArgs";
import { WastageWhereUniqueInput } from "./WastageWhereUniqueInput";
import { WastageUpdateInput } from "./WastageUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WastageControllerBase {
  constructor(
    protected readonly service: WastageService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Wastage })
  @nestAccessControl.UseRoles({
    resource: "Wastage",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createWastage(
    @common.Body() data: WastageCreateInput
  ): Promise<Wastage> {
    return await this.service.createWastage({
      data: {
        ...data,

        rawMaterial: data.rawMaterial
          ? {
              connect: data.rawMaterial,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        date: true,
        id: true,
        quantity: true,

        rawMaterial: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Wastage] })
  @ApiNestedQuery(WastageFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Wastage",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async wastages(@common.Req() request: Request): Promise<Wastage[]> {
    const args = plainToClass(WastageFindManyArgs, request.query);
    return this.service.wastages({
      ...args,
      select: {
        createdAt: true,
        date: true,
        id: true,
        quantity: true,

        rawMaterial: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Wastage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Wastage",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async wastage(
    @common.Param() params: WastageWhereUniqueInput
  ): Promise<Wastage | null> {
    const result = await this.service.wastage({
      where: params,
      select: {
        createdAt: true,
        date: true,
        id: true,
        quantity: true,

        rawMaterial: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Wastage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Wastage",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateWastage(
    @common.Param() params: WastageWhereUniqueInput,
    @common.Body() data: WastageUpdateInput
  ): Promise<Wastage | null> {
    try {
      return await this.service.updateWastage({
        where: params,
        data: {
          ...data,

          rawMaterial: data.rawMaterial
            ? {
                connect: data.rawMaterial,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          date: true,
          id: true,
          quantity: true,

          rawMaterial: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Wastage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Wastage",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteWastage(
    @common.Param() params: WastageWhereUniqueInput
  ): Promise<Wastage | null> {
    try {
      return await this.service.deleteWastage({
        where: params,
        select: {
          createdAt: true,
          date: true,
          id: true,
          quantity: true,

          rawMaterial: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
