/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RawMaterialService } from "../rawMaterial.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RawMaterialCreateInput } from "./RawMaterialCreateInput";
import { RawMaterial } from "./RawMaterial";
import { RawMaterialFindManyArgs } from "./RawMaterialFindManyArgs";
import { RawMaterialWhereUniqueInput } from "./RawMaterialWhereUniqueInput";
import { RawMaterialUpdateInput } from "./RawMaterialUpdateInput";
import { InventoryFindManyArgs } from "../../inventory/base/InventoryFindManyArgs";
import { Inventory } from "../../inventory/base/Inventory";
import { InventoryWhereUniqueInput } from "../../inventory/base/InventoryWhereUniqueInput";
import { WastageFindManyArgs } from "../../wastage/base/WastageFindManyArgs";
import { Wastage } from "../../wastage/base/Wastage";
import { WastageWhereUniqueInput } from "../../wastage/base/WastageWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RawMaterialControllerBase {
  constructor(
    protected readonly service: RawMaterialService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: RawMaterial })
  @nestAccessControl.UseRoles({
    resource: "RawMaterial",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRawMaterial(
    @common.Body() data: RawMaterialCreateInput
  ): Promise<RawMaterial> {
    return await this.service.createRawMaterial({
      data: data,
      select: {
        cost: true,
        createdAt: true,
        id: true,
        name: true,
        unit: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [RawMaterial] })
  @ApiNestedQuery(RawMaterialFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "RawMaterial",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async rawMaterials(@common.Req() request: Request): Promise<RawMaterial[]> {
    const args = plainToClass(RawMaterialFindManyArgs, request.query);
    return this.service.rawMaterials({
      ...args,
      select: {
        cost: true,
        createdAt: true,
        id: true,
        name: true,
        unit: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: RawMaterial })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RawMaterial",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async rawMaterial(
    @common.Param() params: RawMaterialWhereUniqueInput
  ): Promise<RawMaterial | null> {
    const result = await this.service.rawMaterial({
      where: params,
      select: {
        cost: true,
        createdAt: true,
        id: true,
        name: true,
        unit: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: RawMaterial })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RawMaterial",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRawMaterial(
    @common.Param() params: RawMaterialWhereUniqueInput,
    @common.Body() data: RawMaterialUpdateInput
  ): Promise<RawMaterial | null> {
    try {
      return await this.service.updateRawMaterial({
        where: params,
        data: data,
        select: {
          cost: true,
          createdAt: true,
          id: true,
          name: true,
          unit: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: RawMaterial })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RawMaterial",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRawMaterial(
    @common.Param() params: RawMaterialWhereUniqueInput
  ): Promise<RawMaterial | null> {
    try {
      return await this.service.deleteRawMaterial({
        where: params,
        select: {
          cost: true,
          createdAt: true,
          id: true,
          name: true,
          unit: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/inventories")
  @ApiNestedQuery(InventoryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Inventory",
    action: "read",
    possession: "any",
  })
  async findInventories(
    @common.Req() request: Request,
    @common.Param() params: RawMaterialWhereUniqueInput
  ): Promise<Inventory[]> {
    const query = plainToClass(InventoryFindManyArgs, request.query);
    const results = await this.service.findInventories(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        quantity: true,

        rawMaterial: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/inventories")
  @nestAccessControl.UseRoles({
    resource: "RawMaterial",
    action: "update",
    possession: "any",
  })
  async connectInventories(
    @common.Param() params: RawMaterialWhereUniqueInput,
    @common.Body() body: InventoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inventories: {
        connect: body,
      },
    };
    await this.service.updateRawMaterial({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/inventories")
  @nestAccessControl.UseRoles({
    resource: "RawMaterial",
    action: "update",
    possession: "any",
  })
  async updateInventories(
    @common.Param() params: RawMaterialWhereUniqueInput,
    @common.Body() body: InventoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inventories: {
        set: body,
      },
    };
    await this.service.updateRawMaterial({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/inventories")
  @nestAccessControl.UseRoles({
    resource: "RawMaterial",
    action: "update",
    possession: "any",
  })
  async disconnectInventories(
    @common.Param() params: RawMaterialWhereUniqueInput,
    @common.Body() body: InventoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inventories: {
        disconnect: body,
      },
    };
    await this.service.updateRawMaterial({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/wastages")
  @ApiNestedQuery(WastageFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Wastage",
    action: "read",
    possession: "any",
  })
  async findWastages(
    @common.Req() request: Request,
    @common.Param() params: RawMaterialWhereUniqueInput
  ): Promise<Wastage[]> {
    const query = plainToClass(WastageFindManyArgs, request.query);
    const results = await this.service.findWastages(params.id, {
      ...query,
      select: {
        createdAt: true,
        date: true,
        id: true,
        quantity: true,

        rawMaterial: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/wastages")
  @nestAccessControl.UseRoles({
    resource: "RawMaterial",
    action: "update",
    possession: "any",
  })
  async connectWastages(
    @common.Param() params: RawMaterialWhereUniqueInput,
    @common.Body() body: WastageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      wastages: {
        connect: body,
      },
    };
    await this.service.updateRawMaterial({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/wastages")
  @nestAccessControl.UseRoles({
    resource: "RawMaterial",
    action: "update",
    possession: "any",
  })
  async updateWastages(
    @common.Param() params: RawMaterialWhereUniqueInput,
    @common.Body() body: WastageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      wastages: {
        set: body,
      },
    };
    await this.service.updateRawMaterial({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/wastages")
  @nestAccessControl.UseRoles({
    resource: "RawMaterial",
    action: "update",
    possession: "any",
  })
  async disconnectWastages(
    @common.Param() params: RawMaterialWhereUniqueInput,
    @common.Body() body: WastageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      wastages: {
        disconnect: body,
      },
    };
    await this.service.updateRawMaterial({
      where: params,
      data,
      select: { id: true },
    });
  }
}
